application: duckspeakapp
version: 1
runtime: go
api_version: go1

handlers:
- url: /cron/.*
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: 50ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  API_BASE: "https://duckspeakapp.appspot.com"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- vendor/