application: duckspeakapp
version: 1
runtime: go
api_version: go1

handlers:
- url: /cron/.*
  script: _go_app
  secure: always
  login: admin

- url: /auth/admin
  script: _go_app
  secure: always
  login: admin

- url: /.*
  script: _go_app
  secure: always

instance_class: F1
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: automatic
  min_pending_latency: 50ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

env_variables:
  AUTH_ISSUER: "https://duckspeakapp.com"
  AUTH_SECRET: "699b636c8387a3b79ad42c57241872115e13d0d6ce12614eef3cf581b3733dba6e946733cdd85c32"

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- vendor/